# Install command:
# brew bundle install --file=Brewfile

brew "age"
brew "coreutils"
brew "eslint"
brew "fzf"
brew "git"
brew "golang"
brew "golangci-lint"
brew "gosec"
brew "jq"
brew "mas"
brew "neovim"
brew "nmap"
brew "ripgrep"
brew "stow"
brew "tectonic"
brew "tldr"
brew "tmux"
brew "tree"

brew "bat"
brew "bcrypt"
brew "bzip2"
brew "cfssl"
brew "cloc"
brew "cmake"
brew "cookiecutter"
brew "fd"
brew "ghz"
brew "graphviz"
brew "httpie"
brew "iperf"
brew "ldns"
brew "mtr"
brew "semgrep"
brew "sha3sum"
brew "sipcalc"
brew "sslscan"
brew "unzip"
brew "wget"
brew "ykman"

cask "affinity-designer"
cask "alfred"
cask "contexts"
cask "discord"
cask "docker"
cask "font-computer-modern"
cask "goldendict"
cask "google-chrome"
cask "istat-menus"
cask "iterm2"
cask "kap"
cask "keepassxc"
cask "krita"
cask "parallels"
cask "sage"
cask "utm"
cask "visual-studio-code"

#cask "logitech-options"
#cask "obinskit"
cask "calibre"
cask "cursorcerer"
cask "devdocs"
cask "obs"
cask "postman"
cask "spotify"
cask "wireshark"
cask "zoom"

tap "homebrew/cask-fonts"
cask "font-computer-modern"
cask "font-fira-code"
cask "font-iosevka"

tap "github/gh"
brew "gh"
