# Install command:
# brew bundle install --file=Brewfile

brew "age"
brew "coreutils"
brew "eslint"
brew "fzf"
brew "git"
brew "golang"
brew "golangci-lint"
brew "jq"
brew "mas"
brew "neovim"
brew "ripgrep"
brew "stow"
brew "tectonic"
brew "tldr"
brew "tmux"
brew "tree"

cask "affinity-designer"
cask "alfred"
cask "contexts"
cask "discord"
cask "docker"
cask "dropbox"
cask "font-computer-modern"
cask "goldendict"
cask "google-chrome"
cask "istat-menus"
cask "iterm2"
cask "java"
cask "kap"
cask "keepassxc"
cask "krita"
cask "parallels"
cask "sage"
cask "utm"
cask "visual-studio-code"

tap "homebrew/cask-fonts"
cask "font-iosevka"

tap "github/gh"
brew "gh"
