### See https://github.com/be5invis/Iosevka/blob/master/doc/custom-build.md for comprehensive
### documentation of the options in this file

[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
webfont-formats = ['ttf']

  [buildPlans.iosevka-custom.variants]
  inherits = "ss14"

    [buildPlans.iosevka-custom.variants.design]
    two = "curly-neck-serifless"
    four = "closed-serifless"
    seven = "bend-serifless"
    eight = "crossing-asymmetric"
    zero = "tall-slashed"
    capital-w = "straight-serifless"
    f = "flat-hook-serifless-crossbar-at-x-height"
    g = "double-storey"
    t = "flat-hook-short-neck"
    w = "straight-serifless"
    lower-upsilon = "casual-serifed"
    cyrl-ef = "serifless"
    punctuation-dot = "round"
    tilde = "low"
    asterisk = "hex-low"
    brace = "straight"
    number-sign = "slanted"
    ampersand = "upper-open"
    at = "fourfold"

[buildPlans.iosevka-custom.weights.ExtraLight]
shape = 200
menu = 200
css = 200

[buildPlans.iosevka-custom.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.iosevka-custom.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-custom.weights.Bold]
shape = 700
menu = 700
css = 700



[buildPlans.iosevka-custom-term]
family = "Iosevka Custom Term"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
webfont-formats = ['ttf']

  [buildPlans.iosevka-custom-term.variants]
  inherits = "ss14"

    [buildPlans.iosevka-custom-term.variants.design]
    two = "curly-neck-serifless"
    four = "closed-serifless"
    seven = "bend-serifless"
    eight = "crossing-asymmetric"
    zero = "tall-slashed"
    capital-w = "straight-serifless"
    f = "flat-hook-serifless-crossbar-at-x-height"
    g = "double-storey"
    t = "flat-hook-short-neck"
    w = "straight-serifless"
    lower-upsilon = "casual-serifed"
    cyrl-ef = "serifless"
    punctuation-dot = "round"
    tilde = "low"
    asterisk = "hex-low"
    brace = "straight"
    number-sign = "slanted"
    ampersand = "upper-open"
    at = "fourfold"

[buildPlans.iosevka-custom-term.weights.ExtraLight]
shape = 200
menu = 200
css = 200

[buildPlans.iosevka-custom-term.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.iosevka-custom-term.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-custom-term.weights.Bold]
shape = 700
menu = 700
css = 700
