### See https://github.com/be5invis/Iosevka/blob/master/doc/custom-build.md for comprehensive
### documentation of the options in this file

[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.iosevka-custom.variants]
  inherits = "ss14"

    [buildPlans.iosevka-custom.variants.design]
    two = "curly-neck-serifless"
    four = "closed-serifless"
    seven = "bend-serifless"
    eight = "crossing"
    zero = "tall-slashed"
    capital-w = "straight-serifless"
    f = "flat-hook-serifless-crossbar-at-x-height"
    g = "double-storey"
    t = "flat-hook-short-neck"
    # w = "straight-serifless"
    lower-upsilon = "casual-serifed"
    asterisk = "hex-low"
    brace = "straight"
    at = "fourfold"

[buildPlans.iosevka-custom-term]
family = "Iosevka Custom Term"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
webfont-formats = ['ttf']

  [buildPlans.iosevka-custom-term.variants]
  inherits = "ss14"

    [buildPlans.iosevka-custom-term.variants.design]
    two = "curly-neck-serifless"
    four = "closed-serifless"
    seven = "bend-serifless"
    eight = "crossing"
    zero = "tall-slashed"
    capital-w = "straight-serifless"
    f = "flat-hook-serifless-crossbar-at-x-height"
    g = "double-storey"
    t = "flat-hook-short-neck"
    # w = "straight-serifless"
    lower-upsilon = "casual-serifed"
    asterisk = "hex-low"
    brace = "straight"
    at = "fourfold"