
[mgr]
linemode       = "size"
ratio          = [2,4,4]
scrolloff      = 3
title_format   = "📂 {cwd}"

show_symlink = true
sort_dir_first = true

[preview]
max_width       = 1200
max_height      = 1080

